const id=document.body.dataset.tool;
const data={
 'word-counter':['Word Counter','Count words, characters, sentences, paragraphs, and estimated reading time as you write.','Paste or type text below. Your counts update instantly.'],
 'character-counter':['Character Counter','Count every character in your text and check common copy limits.','Paste or type text below.'],
 'case-converter':['Case Converter','Convert text between uppercase, lowercase, Title Case, camelCase, and snake_case.','Paste text then choose a format.'],
 'remove-duplicate-lines':['Remove Duplicate Lines','Remove repeated lines from a list while preserving their original order.','Paste one item per line.'],
 'sort-lines':['Sort Lines','Sort a list alphabetically in ascending or descending order.','Paste one item per line.'],
 'remove-extra-spaces':['Remove Extra Spaces','Clean extra spaces, tabs, and trailing whitespace from your text.','Paste text to clean.'],
 'remove-line-breaks':['Remove Line Breaks','Turn broken lines into one clean paragraph.','Paste text to join.'],
 'find-and-replace':['Find and Replace','Find a word or phrase and replace it everywhere in your text.','Paste text to edit.'],
 'reading-time':['Reading Time Calculator','Estimate how long readers need to finish an article.','Paste your article below.'],
 'url-slug-generator':['URL Slug Generator','Turn a title into a clean, lowercase, SEO-friendly URL slug.','Type a title or phrase.']};
const [name,desc,placeholder]=data[id];document.querySelector('#tool-name').textContent=name;document.querySelector('#tool-description').textContent=desc;
const input=document.querySelector('#text'),result=document.querySelector('#result'),controls=document.querySelector('#controls');input.placeholder=placeholder;result.style.display='block';result.style.minHeight='88px';
const show=x=>result.textContent=x||'Your result will appear here.';const words=x=>(x.match(/[A-Za-z0-9]+(?:'[A-Za-z]+)?/g)||[]).length;
function live(){let x=input.value;if(id==='word-counter')show(`Words: ${words(x)}\nCharacters: ${[...x].length}\nSentences: ${(x.match(/[.!?]+/g)||[]).length}\nParagraphs: ${x.trim()?x.trim().split(/\n\s*\n/).length:0}\nReading time: ${Math.max(1,Math.ceil(words(x)/200))} min`);else if(id==='character-counter')show(`Characters: ${[...x].length}\nCharacters without spaces: ${x.replace(/\s/g,'').length}\nRemaining to 160: ${Math.max(0,160-[...x].length)}\nRemaining to 280: ${Math.max(0,280-[...x].length)}`);else if(id==='reading-time')show(`Estimated reading time: ${Math.max(1,Math.ceil(words(x)/200))} minute${words(x)>200?'s':''}\n${words(x)} words at 200 words per minute.`);else if(id==='url-slug-generator')show(x.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''));}
if(['word-counter','character-counter','reading-time','url-slug-generator'].includes(id)){input.addEventListener('input',live);live()}else if(id==='case-converter'){controls.innerHTML='<button data-m="upper">UPPERCASE</button><button data-m="lower">lowercase</button><button data-m="title">Title Case</button><button data-m="camel">camelCase</button><button data-m="snake">snake_case</button>'}else if(id==='sort-lines'){controls.innerHTML='<button data-m="asc">A → Z</button><button data-m="desc" class="alt">Z → A</button>'}else if(id==='find-and-replace'){controls.innerHTML='<input id="find" placeholder="Find text" /><input id="replace" placeholder="Replace with" /><button data-m="run">Replace all</button>'}else controls.innerHTML='<button data-m="run">Process text</button>';
controls.addEventListener('click',e=>{let m=e.target.dataset.m;if(!m)return;let x=input.value,out='';if(id==='case-converter'){let a=x.trim().split(/[\s_-]+/);out=m==='upper'?x.toUpperCase():m==='lower'?x.toLowerCase():m==='title'?x.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()):m==='camel'?a.map((v,i)=>i?v[0].toUpperCase()+v.slice(1).toLowerCase():v.toLowerCase()).join(''):a.map(v=>v.toLowerCase()).join('_')}else if(id==='remove-duplicate-lines')out=[...new Set(x.split(/\r?\n/))].join('\n');else if(id==='sort-lines')out=x.split(/\r?\n/).sort((a,b)=>m==='desc'?b.localeCompare(a):a.localeCompare(b)).join('\n');else if(id==='remove-extra-spaces')out=x.replace(/[\t ]+/g,' ').replace(/ *\n */g,'\n').trim();else if(id==='remove-line-breaks')out=x.replace(/\s*\n\s*/g,' ').replace(/ {2,}/g,' ').trim();else if(id==='find-and-replace'){let f=document.querySelector('#find').value,r=document.querySelector('#replace').value;out=f?x.split(f).join(r):x}show(out)});
const utility=document.createElement('div');utility.className='tool-controls';utility.innerHTML='<button type="button" class="alt" data-action="clear">Clear</button><button type="button" data-action="copy">Copy result</button>';document.querySelector('.tool-shell').appendChild(utility);utility.addEventListener('click',async e=>{const action=e.target.dataset.action;if(action==='clear'){input.value='';if(['word-counter','character-counter','reading-time','url-slug-generator'].includes(id))live();else show('Your result will appear here.');input.focus()}if(action==='copy'){const text=result.textContent;if(!text||text==='Your result will appear here.')return;try{await navigator.clipboard.writeText(text);e.target.textContent='Copied ✓'}catch{const helper=document.createElement('textarea');helper.value=text;document.body.append(helper);helper.select();document.execCommand('copy');helper.remove();e.target.textContent='Copied ✓'}setTimeout(()=>e.target.textContent='Copy result',1400)}});
